language: python
sudo: false

env:
  matrix:
    - PYTHON=2.7
    - PYTHON=2.7
    - PYTHON=3.3
    - PYTHON=3.4
    - PYTHON=3.5


before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create -n test-environment python=$PYTHON
  - conda install -c conda-forge dask toolz cytoolz pytest
  - source activate test-environment
  - pip install pytest-pythonpath

# command to run tests, e.g. python setup.py test
script: pytest
